- name: Disable automatic Updates
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
    name: NoAutoUpdate
    type: dword
    data: 1

- name: Stop and disable Windows Update service
  win_service:
    name: wuauserv
    start_mode: disabled
    state: stopped
